"use strict";

const data = {
  user1: {
    firstName: "Ashley",
    lastName: "DevMaster",
    title: "",
    position: "",
    competencies: "",
    interests: "",
    offer: "",
    seek: "",
    organization: "",
  },
  user2: {
    firstName: "Maykal",
    lastName: "StrongMan",
    title: "",
    position: "",
    competencies: "",
    interests: "",
    offer: "",
    seek: "",
    organization: "",
  },
  user3: {
    firstName: "Rafael",
    lastName: "Oliveira",
    title: "",
    position: "",
    competencies: "",
    interests: "",
    offer: "",
    seek: "",
    organization: "",
  },
  user4: {
    firstName: "John",
    lastName: "Doe",
    title: "",
    position: "",
    competencies: "",
    interests: "",
    offer: "",
    seek: "",
    organization: "",
  },
  user5: {
    firstName: "Maria",
    lastName: "Theresa",
    title: "",
    position: "",
    competencies: "",
    interests: "",
    offer: "",
    seek: "",
    organization: "",
  },
};
