"use strict";

const data = {
  user1: {
    firstName: "Peter",
    lastName: "Stein",
    email: "peterstein@matrix-ggmbh.de",
    phone: 491623836497,
    interests: ["Menschzentriertes Design", "Code Patterns"],
    description:
      "Kontaktiert mich gern, falls ihr Probleme habt, euch kommende Features der Plattform interessieren oder ihr euch einfach über Technologien austauschen wollt.",
    activityAreas: ["Düsseldorf"],
    competencies: ["Webentwicklung"],
    offer: ["Digitale Koptenzen"],
    seek: ["Kontakt zu Unternehmen"],
    website: "nash@matrix-ggmbh.de",
    organization: "Matrix gGmbH",
    _id: "634a886839a458483a65bb8b",
    dateCreated: "2022-10-15T10:16:08.107Z",
    __v: 0,
  },
  user2: {
    firstName: "Peter",
    lastName: "Stein",
    email: "peterstein@matrix-ggmbh.de",
    phone: 491623836497,
    interests: ["Menschzentriertes Design", "Code Patterns"],
    description:
      "Kontaktiert mich gern, falls ihr Probleme habt, euch kommende Features der Plattform interessieren oder ihr euch einfach über Technologien austauschen wollt.",
    activityAreas: ["Düsseldorf"],
    competencies: ["Webentwicklung"],
    offer: ["Digitale Koptenzen"],
    seek: ["Kontakt zu Unternehmen"],
    website: "nash@matrix-ggmbh.de",
    organization: "Matrix gGmbH",
    _id: "634a886839a458483a65bb8b",
    dateCreated: "2022-10-15T10:16:08.107Z",
    __v: 0,
  },
  user3: {
    firstName: "Peter",
    lastName: "Stein",
    email: "peterstein@matrix-ggmbh.de",
    phone: 491623836497,
    interests: ["Menschzentriertes Design", "Code Patterns"],
    description:
      "Kontaktiert mich gern, falls ihr Probleme habt, euch kommende Features der Plattform interessieren oder ihr euch einfach über Technologien austauschen wollt.",
    activityAreas: ["Düsseldorf"],
    competencies: ["Webentwicklung"],
    offer: ["Digitale Koptenzen"],
    seek: ["Kontakt zu Unternehmen"],
    website: "nash@matrix-ggmbh.de",
    organization: "Matrix gGmbH",
    _id: "634a886839a458483a65bb8b",
    dateCreated: "2022-10-15T10:16:08.107Z",
    __v: 0,
  },
  user4: {
    firstName: "Peter",
    lastName: "Stein",
    email: "peterstein@matrix-ggmbh.de",
    phone: 491623836497,
    interests: ["Menschzentriertes Design", "Code Patterns"],
    description:
      "Kontaktiert mich gern, falls ihr Probleme habt, euch kommende Features der Plattform interessieren oder ihr euch einfach über Technologien austauschen wollt.",
    activityAreas: ["Düsseldorf"],
    competencies: ["Webentwicklung"],
    offer: ["Digitale Koptenzen"],
    seek: ["Kontakt zu Unternehmen"],
    website: "nash@matrix-ggmbh.de",
    organization: "Matrix gGmbH",
    _id: "634a886839a458483a65bb8b",
    dateCreated: "2022-10-15T10:16:08.107Z",
    __v: 0,
  },
  user5: {
    firstName: "Peter",
    lastName: "Stein",
    email: "peterstein@matrix-ggmbh.de",
    phone: 491623836497,
    interests: ["Menschzentriertes Design", "Code Patterns"],
    description:
      "Kontaktiert mich gern, falls ihr Probleme habt, euch kommende Features der Plattform interessieren oder ihr euch einfach über Technologien austauschen wollt.",
    activityAreas: ["Düsseldorf"],
    competencies: ["Webentwicklung"],
    offer: ["Digitale Koptenzen"],
    seek: ["Kontakt zu Unternehmen"],
    website: "nash@matrix-ggmbh.de",
    organization: "Matrix gGmbH",
    _id: "634a886839a458483a65bb8b",
    dateCreated: "2022-10-15T10:16:08.107Z",
    __v: 0,
  },
};
